### ISSUE TITLE
Load data with null values

### ISSUE THREAD

**Issue by sheldon-sminq** [kevindb/jquery-load-json#22] opened 2017-06-14 12:24 UTC
We use this plugin extensively, recently updated to the latest 1.3.3 version, and are facing this issue

```

`Uncaught TypeError: Cannot read property 'constructor' of null
   at h (jquery.loadJSON.min.js:18)
   at h (jquery.loadJSON.min.js:18)
   at HTMLFormElement.<anonymous> (jquery.loadJSON.min.js:18)
   at Function.each (jQuery-2.1.4.min.js:2)
   at n.fn.init.each (jQuery-2.1.4.min.js:2)
   at n.fn.init.a.fn.loadJSON (jquery.loadJSON.min.js:18)
   at loadModal (queueConfiguration.js:82)
   at HTMLAnchorElement.onclick (queueConfigurationList.html:1)`

```

**Comment by kevindb** [comment] 2017-06-14 13:25
Duplicate of #23

**Closed by kevindb** 2017-06-14 13:25 UTC
Labels: duplicate
